---
name: our_gfg
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^2.4.1
  cached_network_image: ^2.3.3
  cloud_firestore: ^0.14.1+3
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.0+1
  font_awesome_flutter: ^8.10.0
  intl: ^0.16.1
  shimmer: ^1.1.2
  url_launcher: ^5.7.5
  webview_flutter: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^1.1.1
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
